---

- name: ensure visual-studio-code installed by umake
  stat:
    path: ~/.local/share/umake/ide/visual-studio-code
  register: install_dir

- name: uninstall visual-studio-code if installed by umake
  shell: umake ide visual-studio-code --remove
  when: install_dir.stat.exists

- name: add apt key
  become: true
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg

- name: add apt repository
  become: true
  apt_repository:
    repo: >-
      deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    filename: vscode
    state: present

- name: install packages
  become: true
  apt:
    name: code
    update_cache: yes  # yamllint disable-line rule:truthy

- name: install plugins
  include_tasks: inner/install_plugin.yml
  with_items: "{{ vscode_plugins }}"
  loop_control:
    loop_var: vscode_plugin

- name: create temporary working directory
  tempfile:
    state: directory
  register: tmpdir

- name: show temporary working directory path
  debug:
    msg: "{{ tmpdir.path }}"

- name: copy customized settings file to temporary working directory
  copy:
    src: customized_settings.json
    dest: "{{ tmpdir.path }}/customized_settings.json"
    mode: 0664

- name: remove CR code in customized settings file
  replace:
    dest: "{{ tmpdir.path }}/customized_settings.json"
    regexp: '\r'
    replace: ''

- name: check whether already exist vaild common settings
  shell: |-
    test -s "{{ vscode_common_settings_file_path }}"
  register: checked_result
  failed_when: checked_result.rc not in [0, 1]

- name: initialize common settings
  shell: |-
    echo '{}' > "{{ vscode_common_settings_file_path }}"
  when: checked_result.rc == 1

- name: merge customized settings into common settings
  shell: |-
    jq --slurp --indent 4 '.[0] * .[1]' \
      "{{ vscode_common_settings_file_path }}" \
      "{{ tmpdir.path }}/customized_settings.json" \
    | sponge "{{ vscode_common_settings_file_path }}"

- name: remove temporary working directory
  file:
    path: "{{ tmpdir.path }}"
    state: absent

- name: add locale.json
  copy:
    src: locale.json
    dest: "/home/vagrant/.config/Code/User/locale.json"
    mode: 0664
