---

- name: change global git config
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - name: core.editor
      value: nano
    - name: log.decorate
      value: short
    - name: push.default
      value: simple
    - name: pull.ff
      value: only
