---

- name: change global git config
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - name: log.decorate
      value: short
    - name: push.default
      value: simple
