---

- name: add apt repository
  become: true
  apt_repository:
    repo: ppa:git-core/ppa

- name: install packages
  become: true
  apt:
    name: git
    state: latest
    update_cache: yes  # yamllint disable-line rule:truthy
