---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: xenial
    image: ubuntu:16.04
    capabilities:
      - SYS_PTRACE
    security_opts:
      - seccomp=unconfined
  - name: bionic
    image: ubuntu:18.04
    capabilities:
      - SYS_PTRACE
    security_opts:
      - seccomp=unconfined
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
