---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: cplusplus-bionic
    image: ubuntu:18.04
    dockerfile: DockerfileExtended.j2
    capabilities:
      - SYS_PTRACE
    security_opts:
      - seccomp=unconfined
  # TODO: support archlinux
  # - name: cplusplus-archlinux
  #   image: archlinux
  #   dockerfile: DockerfileExtended.j2
  #   capabilities:
  #     - SYS_PTRACE
  #   security_opts:
  #     - seccomp=unconfined
provisioner:
  name: ansible
  options:
    user: vagrant
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
