---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: cplusplus-xenial
    image: ubuntu:16.04
    capabilities:
      - SYS_PTRACE
    security_opts:
      - seccomp=unconfined
  - name: cplusplus-bionic
    image: ubuntu:18.04
    capabilities:
      - SYS_PTRACE
    security_opts:
      - seccomp=unconfined
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
