---

matrix:
  include:
    - language: python
      python:
        - "3.6"
      install:
        - pip install pipenv
        - pipenv install --dev
      script:
        - make yamllint
    - language: node_js
      node_js:
        - "node"
      install:
        - yarn
      script:
        - make jsonlint
      cache:
        yarn: true
