---

matrix:
  include:
    - language: python
      python:
        - "3.6"
      install:
        - pip install pipenv
        - pipenv install --dev
      script:
        - make yamllint
    - services:
        - docker
      script:
        - make up
        - docker-compose exec node yarn install -d
        - docker-compose exec node make jsonlint
        - make down
