version: "2"

services:
  node:
    build: dockerfiles/node
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
  python:
    build: dockerfiles/python
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
