---

- name: configure default profile
  shell: |-
    gconftool-2 \
      --set "/apps/gnome-terminal/profiles/Default/{{ item.key }}" \
      --type "{{ item.type }}" "{{ item.value }}"
  with_items:
    # Uncheck option "Use the system fixed width font"
    - key: "use_system_font"
      type: "bool"
      value: false
    # Uncheck option "Use colours from system theme"
    - key: "use_theme_colors"
      type: "bool"
      value: "false"
    # Select palette "Gray on black"
    - key: "background_color"
      type: "string"
      value: "#000000000000"
    - key: "foreground_color"
      type: "string"
      value: "#AAAAAAAAAAAA"
    # Select "Tango" as "Built-in schemes"
    - key: "palette"
      type: "string"
      value: >-
        "#000000000000:#CCCC00000000:#4E4E9A9A0606:#C4C4A0A00000:#34346565A4A4:#757550507B7B:#060698209A9A:#D3D3D7D7CFCF:#555557575353:#EFEF29292929:#8A8AE2E23434:#FCFCE9E94F4F:#72729F9FCFCF:#ADAD7F7FA8A8:#3434E2E2E2E2:#EEEEEEEEECEC"
