---

- name: add apt repository
  become: yes
  apt_repository:
    repo: >-
      deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main
    filename: llvm
    state: present

- name: install package
  become: yes
  apt:
    name: clang-format
    allow_unauthenticated: yes
