---

- name: install required packages
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - dh-autoreconf
    - libcurl4-gnutls-dev
    - libexpat1-dev
    - gettext
    - libz-dev
    - libssl-dev
    - asciidoc
    - xmlto
    - docbook2x
    - libperl4-corelibs-perl  # for getopt

- name: ensure downloaded
  stat:
    path: /usr/local/src/git-{{ git_version }}
  register: download_directory

- name: download
  become: yes
  unarchive:
    src: https://github.com/git/git/archive/v{{ git_version }}.tar.gz
    dest: /usr/local/src
    remote_src: yes
    creates: /usr/local/src/git-{{ git_version }}
  when: not download_directory.stat.exists

- name: compile and install
  become: yes
  shell: "{{ item }}"
  args:
    chdir: /usr/local/src/git-{{ git_version }}
  with_items:
    - make configure
    - ./configure --prefix=/usr/local/stow/git-{{ git_version }}
    - make all doc info
    - make install install-doc install-html install-info

- name: stow
  become: yes
  shell: stow -R git-{{ git_version }}
  args:
    chdir: /usr/local/stow
