---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: gui-applications-bionic
    image: ubuntu:18.04
    # TODO
    # dockerfile: DockerfileExtended.j2
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
