---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: gui-applications-xenial
    image: ubuntu:16.04
  - name: gui-applications-bionic
    image: ubuntu:18.04
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
