---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: xenial
    image: ubuntu:16.04
    dockerfile: DockerfileExtended.j2
  - name: bionic
    image: ubuntu:18.04
    dockerfile: DockerfileExtended.j2
provisioner:
  name: ansible
  options:
    user: vagrant
verifier:
  name: testinfra
lint: |
  set -e
  yamllint .
  ansible-lint -x 701
  flake8
