---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: xenial
    image: ubuntu:16.04
    dockerfile: DockerfileExtended.j2
  - name: bionic
    image: ubuntu:18.04
    dockerfile: DockerfileExtended.j2
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ["701"]
  options:
    user: vagrant
verifier:
  name: testinfra
  lint:
    name: flake8
