---

- name: put pyenv.bashrc in ~/.bashrc.d
  copy:
    src: bashrc
    dest: ~/.bashrc.d/pyenv.bashrc
    mode: 0755

- name: check whether already installed pyenv
  shell: |-
    . ~/.bashrc.d/pyenv.bashrc
    which pyenv
  register: checked_result
  changed_when: False
  failed_when: checked_result.rc not in [0, 1]
  when:
    - ansible_distribution == "Ubuntu"

- name: install pyenv
  when: checked_result.rc == 1
  block:
    - name: install requirements
      become: yes
      apt:
        name:
          - curl
          - git
      when:
        - ansible_distribution == "Ubuntu"
    - name: create temporary working directory
      tempfile:
        state: directory
      register: tmpdir
    - name: download pyenv-installer
      get_url:
        url: https://pyenv.run
        dest: "{{ tmpdir.path }}/pyenv-installer"
    - name: execute pyenv-installer
      command: "bash {{ tmpdir.path }}/pyenv-installer"
    - name: remove temporary working directory
      file:
        path: "{{ tmpdir.path }}"
        state: absent
