---

- name: uninstall pyenv if already installed
  file:
    path: /home/vagrant/.pyenv
    state: absent

- name: create temporary working directory
  tempfile:
    state: directory
  register: tmpdir

- name: download pyenv-installer
  get_url:
    url: https://pyenv.run
    dest: "{{ tmpdir.path }}/pyenv-installer"

- name: execute pyenv-installer
  command: "bash {{ tmpdir.path }}/pyenv-installer"

- name: remove temporary working directory
  file:
    path: "{{ tmpdir.path }}"
    state: absent

- name: put bashrc file in ~/.bashrc.d
  copy:
    src: bashrc
    dest: /home/vagrant/.bashrc.d/pyenv.bashrc
    mode: 0755
