---

- name: ensure downloaded
  stat:
    path: /usr/local/src/cquery-{{ cquery_version }}
  register: download_directory

- name: download
  become: yes
  unarchive:
    src: https://github.com/cquery-project/cquery/releases/download/v{{ cquery_version }}/cquery-v{{ cquery_version }}-x86_64-unknown-linux-gnu.tar.xz
    dest: /usr/local/src
    remote_src: yes
    creates: /usr/local/src/cquery-v{{ cquery_version }}-x86_64-unknown-linux-gnu
  when: not download_directory.stat.exists

- name: create directory
  become: yes
  file:
    path: /usr/local/stow/cquery-{{ cquery_version }}
    state: directory

- name: install
  become: yes
  command: cp -rp bin /usr/local/stow/cquery-{{ cquery_version }}
  args:
    chdir: /usr/local/src/cquery-v{{ cquery_version }}-x86_64-unknown-linux-gnu

- name: stow
  become: yes
  shell: stow -R cquery-{{ cquery_version }}
  args:
    chdir: /usr/local/stow
