---

- name: install packages
  become: true
  apt:
    name: samba

- name: add config file
  become: true
  copy:
    src: smb.conf
    dest: /etc/samba/
    mode: 0644

- name: remove CR code in config file
  become: true
  replace:
    dest: /etc/samba/smb.conf
    regexp: '\r'
    replace: ''

- name: add samba user
  become: true
  shell: |-
    echo '{{ password }}\n{{ password }}\n' \
    | smbpasswd -as "{{ password }}"

- name: restart services
  become: true
  service:
    name: samba
    state: restarted
