---
- name: verify
  hosts: all
  tasks:
    - name: assert test environment
      block:
        - name: determine remote user
          command: whoami
          register: result
          changed_when: False
        - name: assert remote user
          assert:
            that:
              - result.stdout == "vagrant"
            fail_msg: "actual result is {{ result.stdout }}"
    - name: test command existence
      command: bash -c "type {{ item }}"
      register: result
      changed_when: False
      with_items:
        - docker
        - docker-compose
    - name: test docker command usability
      block:
        - name: reboot machine to apply changes
          # avoid rebooting in role because it causes failure in local provision
          become: yes
          reboot: null
        - name: assert docker command usability
          command: docker run --rm hello-world
