---

vscode_plugins:
  # ----------------------------------------------------------------------------
  # Common
  # ----------------------------------------------------------------------------
  - wraith13.wandbox-vscode
  #
  #
  # ----------------------------------------------------------------------------
  # C++
  # ----------------------------------------------------------------------------
  - ajshort.include-autocomplete
  - mitaki28.vscode-clang
  - twxs.cmake
  - xaver.clang-format
  # MEMO: Need gnu-global installation to use this.
  # - austin.code-gnu-global
  #
  # MEMO: Some problems exists.
  #         * navagation include path (Need to edit c_cpp_properties.json)
  # - ms-vscode.cpptools
  #
  #
  # ----------------------------------------------------------------------------
  # Docker
  # ----------------------------------------------------------------------------
  - PeterJausovec.vscode-docker
  #
  #
  # ----------------------------------------------------------------------------
  # Java
  # ----------------------------------------------------------------------------
  - redhat.java
  #
  #
  # ----------------------------------------------------------------------------
  # Markdown
  # ----------------------------------------------------------------------------
  - DavidAnson.vscode-markdownlint
  - shuworks.vscode-table-formatter
  #
  #
  # ----------------------------------------------------------------------------
  # Protocol buffers
  # ----------------------------------------------------------------------------
  - zxh404.vscode-proto3
  #
  #
  # ----------------------------------------------------------------------------
  # Python
  # ----------------------------------------------------------------------------
  - donjayamanne.python
  #
  #
  # ----------------------------------------------------------------------------
  # Restructured text
  # ----------------------------------------------------------------------------
  - lextudio.restructuredtext
  #
  #
  # ----------------------------------------------------------------------------
  # Vagrant
  # ----------------------------------------------------------------------------
  - marcostazi.vs-code-vagrantfile
  #
  #
  # ----------------------------------------------------------------------------
  # Xml
  # ----------------------------------------------------------------------------
  # TODO: Add xml formatter
