---

- hosts: all
  roles:
    - distribution
    - apt

# common roles (tested by molecule)
- hosts: all
  roles:
    - cplusplus
    - git
    - gui-applications
    - nkf
    - python
    - shellcheck
    - vscode
    - xmllint
    - zip

# common roles (not-tested by molecule)
- hosts: all
  roles:
    - bash-completion
    - docker
    - font
    - i3
    - inotify
    - inputrc
    - localization
    - prompt
    - samba
    - swap
    - xdm
    - xfce4-terminal

- import_playbook: ubuntu-xenial.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "16.04"
