---

- name: setup
  hosts: all
  roles:
    - apt

- name: main
  hosts: all
  roles:
    - bash-completion
    - clang-format
    - cquery-xenial
    - docker-compose-xenial
    - firefox
    - font
    - git
    - git-config
    - git-ignore
    - i3-bionic
    - initrc
    - localization
    - meld
    - ninja-build
    - nkf
    - prompt
    - python
    - rtags-xenial
    - samba-xenial
    - vscode
    - xdm
    - xfce4-terminal
