---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: vscode-bionic
    image: ubuntu:18.04
    dockerfile: DockerfileExtended.j2
  # TODO: support archlinux
  # - name: vscode-archlinux
  #   image: archlinux
  #   dockerfile: DockerfileExtended.j2
provisioner:
  name: ansible
  options:
    user: vagrant
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
