---

- name: ensure visual-studio-code installed by umake
  stat:
    path: ~/.local/share/umake/ide/visual-studio-code
  register: install_dir

- name: uninstall visual-studio-code if installed by umake
  shell: umake ide visual-studio-code --remove
  when: install_dir.stat.exists

- name: add apt key
  become: yes
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg

- name: add apt repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    filename: vscode
    state: present

- name: install packages
  become: yes
  apt:
    name: code
    update_cache: yes

- name: install plugins
  shell: code --install-extension "{{ item }}"
  with_items: "{{ vscode_plugins }}"
