---
- name: verify
  hosts: all
  tasks:
    - name: test command existence
      command: bash -c "type {{ item }}"
      register: result
      changed_when: False
      failed_when: result.rc != 0
      with_items:
        - shellcheck
    - name: test shellcheck version
      block:
        - name: get shellcheck version
          command: bash -c "shellcheck --version | grep ^version | awk '{print $2}'"
          register: result
          changed_when: False
          failed_when: result.rc != 0
        - name: assert shellcheck version
          assert:
            that:
              - result.stdout == "0.7.0"
            fail_msg: "actual version is {{ result.stdout }}"
