---

- name: put pyenv.bashrc in ~/.bashrc.d
  copy:
    src: bashrc
    dest: /home/vagrant/.bashrc.d/pyenv.bashrc
    mode: 0755

- name: check whether already installed pyenv
  shell: |-
    . /home/vagrant/.bashrc.d/pyenv.bashrc
    which pyenv
  register: checked_result
  changed_when: False
  failed_when: checked_result.rc not in [0, 1]

- name: install pyenv
  when: checked_result.rc == 1
  block:
    - name: create temporary working directory
      tempfile:
        state: directory
      register: tmpdir
    - name: download pyenv-installer
      get_url:
        url: https://pyenv.run
        dest: "{{ tmpdir.path }}/pyenv-installer"
    - name: execute pyenv-installer
      command: "bash {{ tmpdir.path }}/pyenv-installer"
      register: installer_result
    - debug:
        msg: "{{ installer_result.stdout }}"
    - debug:
        msg: "{{ installer_result.stderr }}"
    - name: remove temporary working directory
      file:
        path: "{{ tmpdir.path }}"
        state: absent
