---

- name: check whether already installed python 3.7.9 # noqa 306
  shell: |-
    . ~/.bashrc.d/pyenv.bashrc
    pyenv versions | grep '^* 3.8.7 (set by /.*)$'
  register: checked_result
  changed_when: False
  failed_when: checked_result.rc not in [0, 1]

- name: install pyenv
  when: checked_result.rc == 1
  block:
    - name: install requirements
      become: yes
      apt:
        name:
          - g++
          - libbz2-dev
          - libffi-dev
          - libreadline-dev
          - libsqlite3-dev
          - libssl-dev
          - make
          - zlib1g-dev
    - name: install python 3.8.7
      shell: |-
        . ~/.bashrc.d/pyenv.bashrc
        pyenv install -s -k 3.8.7
      register: install_result
    - name: show stderr of python 3.8.7 installation and check whether WARNING exists
      debug:
        msg: "{{ install_result.stderr_lines }}"
      failed_when: "{{ install_result.stderr_lines | select('match', '^WARNING: .*$') | list | length > 0 }}"
    - name: set global python version to 3.8.7
      shell: |-
        . ~/.bashrc.d/pyenv.bashrc
        pyenv global 3.8.7
