---

- name: install packages
  become: true
  apt:
    name:
      - fcitx-mozc
      - language-pack-ja

- name: set system locale
  become: true
  shell: localectl set-locale LANG=ja_JP.UTF-8

- name: set timezone
  become: true
  timezone:
    name: Asia/Tokyo
