---

- name: create directory .bashrc.d
  file:
    path: /home/vagrant/.bashrc.d
    state: directory

- name: edit .bashrc to use files in .bashrc.d
  blockinfile:
    path: /home/vagrant/.bashrc
    block: |
      for file in $(ls ~/.bashrc.d/); do
        . ~/.bashrc.d/${file}
      done
