name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: make up
    - run: make lint TTY=false
    - run: make down
    - run: make sync
    - run: make test
