name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: setup poetry
      run: pip install poetry
    - run: make up
    - run: make lint TTY=false
    - run: make down
    - run: make sync
    - run: make test
